In [17]:
#importing os library
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [32]:
#changing the work directory
os.chdir("C:\\Users\\lenovo\\Downloads\\B8DbMusMQZMkNeuPMQRg_Benchmark Model")

In [33]:
#reading Pos_Data and checking the first 5 rows
pos = pd.read_excel("pos_sample.xlsx")
pos.head()

    SKU_ID  Page_traffic  Units_sold Segment
0  SKU1011        4119.0         697  Makeup
1  SKU1011        4074.0        1027  Makeup
2  SKU1011        4897.0        1037  Makeup
3  SKU1011        4783.0        1184  Makeup
4  SKU1011        3789.0         876  Makeup

In [20]:
# view the shape of the data
pos.shape

(3993, 4)

# Steps we will follow to build a model for doing prediction

1. We will begin with dividing the data set into train and valid.
2. Then we will perform mean based and rule based prediction
3. And finally we will evaluate models correctness using MAE

# Step 1: Divide the dataset

In [35]:
#import train_test_split to split data into pos_train and pos_valid
from sklearn.model_selection import train_test_split

In [36]:
#split the data into pos_train and pos_valid|
pos_train, pos_valid= train_test_split(pos, test_size = 0.2, random_state = 7)

In [23]:
#check the shape of train and validation data
pos_train.shape, pos_valid.shape

((3194, 4), (799, 4))

# Step 2: Perform Prediction (Mean Based Prediction)

In [37]:
#overall mean of Units_sold for train data and converting it into integers since units sold cannot be decimals
units_sold_mean = int(pos_train['Units_sold'].mean())

In [38]:
#creating a new column- "Pred_Mean_Units_Sold" in the pos_valid dataframe and assigning the mean of Units_sold from train data 
pos_valid['Pred_Mean_Units_Sold']= units_sold_mean
pos_valid.head()

       SKU_ID  Page_traffic  Units_sold    Segment  Pred_Mean_Units_Sold
638   SKU1377        2170.0        1537   Skincare                  1155
3891   SKU961        3573.0        1547  Hair Care                  1155
2873   SKU481        1808.0        1093   Skincare                  1155
2546   SKU327        2997.0         752     Makeup                  1155
2206   SKU252        2239.0        1287   Skincare                  1155

# Step 3: Evaluate Prediction

In [39]:
#import mean_absolute_error from sklearn.metrics
from sklearn.metrics import mean_absolute_error

In [40]:
#MAE of overall Units_sold mean from pos_train and actual values of 'Units_sold' from pos_valid
mean_absolute_error(pos_valid['Units_sold'], pos_valid['Pred_Mean_Units_Sold'])

308.84480600750936

# Approach 2 (Rule Based Prediction)

# Step 2: Perform Prediction

In [42]:
#calculate mean of Units_sold for pos_train by segment
mean_units_sold_by_segment = pos_train.groupby('Segment')['Units_sold'].mean().astype(int)
mean_units_sold_by_segment

Segment
Hair Care    1178
Makeup       1152
Skincare     1148
Name: Units_sold, dtype: int64

In [47]:
#creating a new column- "Pred_Segment_Mean_Units_Sold" in the pos_valid dataframe and assigning the mean 
pos_valid['Pred_Segment_Mean_Units_Sold'] = pos_valid['Segment'].map(mean_units_sold_by_segment)
#view first 10 rows of pos_valid
pos_valid.head(10)

,SKU_ID,Page_traffic,Units_sold,Segment,Pred_Mean_Units_Sold,Pred_Segment_Mean_Units_Sold
638,SKU1377,2170.0,1537,Skincare,1155,1148
3891,SKU961,3573.0,1547,Hair Care,1155,1178
2873,SKU481,1808.0,1093,Skincare,1155,1148
2546,SKU327,2997.0,752,Makeup,1155,1152
2206,SKU252,2239.0,1287,Skincare,1155,1148
3004,SKU581,4228.0,1410,Makeup,1155,1152
3059,SKU605,3120.0,849,Makeup,1155,1152
1168,SKU1553,4752.0,1140,Makeup,1155,1152
3528,SKU844,2110.0,732,Makeup,1155,1152
1008,SKU1479,5800.0,1183,Hair Care,1155,1178

# Step 3: Evaluate Prediction

In [45]:
#MAE of segment wise Units_sold mean from pos_train and actual values of 'Units_sold' from pos_valid
mean_absolute_error(pos_valid['Units_sold'],pos_valid['Pred_Segment_Mean_Units_Sold'])

309.0863579474343